name: Build and test
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: [ubi7, centos7]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install s2i
      run: conda install -c defusco source-to-image
    - name: Builder image (${{ matrix.base }})
      run: |
        make ${{ matrix.base }}
        docker image ls
    - name: Test builder image (${{ matrix.base }})
      run: PATH=/usr/share/miniconda/bin:$PATH make test-${{ matrix.base }}