name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: [ubi7, ubi8, alpine]
        platform: [linux/amd64, "linux/amd64,linux/arm64"]
        exclude:
          - base: ubi7
            platform: "linux/amd64,linux/arm64"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Builder and push image (${{ matrix.base }})
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          GIT_TAG=`git describe --tags --abbrev=0`
          make ${{ matrix.base }} PLATFORM=${{ matrix.platform }} TAG=latest,$GIT_TAG