name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: [ubi7, centos7]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Builder image (${{ matrix.base }})
        run: |
          make ${{ matrix.base }}
          docker image ls
      - name: Push to Docker Hub (${{ matrix.base }})
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: conda/s2i-anaconda-project-${{ matrix.base }}
          tag_names: true